name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Wrangler
        run: npm i -g wrangler@4

      - name: Template wrangler.toml with bindings
        run: |
          sed -i 's/"__REPLACE_WITH_YOUR_KV_ID__"/"${{ secrets.CF_KV_ID }}"/g' wrangler.toml
          sed -i 's/"__REPLACE_WITH_YOUR_KV_PREVIEW_ID__"/"${{ secrets.CF_KV_PREVIEW_ID || secrets.CF_KV_ID }}"/g' wrangler.toml
          sed -i 's/"__REPLACE_WITH_YOUR_R2_BUCKET__"/"${{ vars.CF_R2_BUCKET }}"/g' wrangler.toml
          sed -i 's/"__REPLACE_WITH_YOUR_R2_PREVIEW_BUCKET__"/"${{ vars.CF_R2_PREVIEW_BUCKET || vars.CF_R2_BUCKET }}"/g' wrangler.toml

      - name: Deploy with Wrangler
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # 可选：Secrets/Vars 可在 Dashboard 配置，也可在此注入
          PERMANENT_PASSWORD: ${{ secrets.PERMANENT_PASSWORD }}
          MAX_FILE_SIZE: ${{ vars.MAX_FILE_SIZE }}
          MAX_TEXT_SIZE: ${{ vars.MAX_TEXT_SIZE }}
          QR_API: ${{ vars.QR_API }}
          NOTICE_TTL_HOURS: ${{ vars.NOTICE_TTL_HOURS }}
          UPLOAD_FILE_RPM: ${{ vars.UPLOAD_FILE_RPM }}
          UPLOAD_TEXT_RPM: ${{ vars.UPLOAD_TEXT_RPM }}
          VERIFY_PERM_RPM: ${{ vars.VERIFY_PERM_RPM }}
          GET_INFO_RPM: ${{ vars.GET_INFO_RPM }}
          DOWNLOAD_RPM: ${{ vars.DOWNLOAD_RPM }}
        run: |
          # 将 GitHub 环境变量透传给 wrangler（仅在本地 wrangler.toml 未设置时生效）
          # Dashboard 上的 Bindings（FILECODEBOX_KV / FILECODEBOX_R2）需提前手动绑定
          wrangler deploy

