name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Wrangler
        run: npm i -g wrangler@4

      # 回退到稳定：不再模板替换 wrangler.toml（使用仓库内已配置的绑定）
      - name: Show Wrangler version
        run: wrangler --version

      - name: Set Cloudflare Secret PERMANENT_PASSWORD (optional)
        if: ${{ secrets.PERMANENT_PASSWORD }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          wrangler secret put PERMANENT_PASSWORD --text "${{ secrets.PERMANENT_PASSWORD }}"

      - name: Deploy with Wrangler
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # 可选：Secrets/Vars 可在 Dashboard 配置，也可在此注入
        run: |
          # 组装 --var 参数，仅对已设置的变量注入，避免覆盖 Dashboard 配置
          wrangler deploy

